AWSTemplateFormatVersion: "2010-09-09"
Description: "Simple stack to create an S3 Bucket"
Resources:
  OurS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: <insert_unique_bucket_name>

